# Generated by Django 4.1.3 on 2022-11-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0002_remove_neighborhood_leader_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Mme", "Mme"), ("Mke", "Mke")],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("dob", models.CharField(blank=True, max_length=20, null=True)),
                ("id_type", models.CharField(max_length=50)),
                ("id_number", models.CharField(max_length=50)),
                ("hamlet", models.CharField(max_length=50)),
                ("house_number", models.CharField(max_length=50)),
                ("work", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="location.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizen",
                "verbose_name_plural": "Citizens",
                "db_table": "dt_citizens",
                "managed": True,
            },
        ),
    ]
