# Generated by Django 4.1.3 on 2022-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                choices=[("Mme", "Mme"), ("Mke", "Mke")], default="Mme", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("NIDA", "NIDA"),
                    ("Leseni ya udereva", "Leseni ya udereva"),
                    ("Passport", "Passport"),
                    ("Kitambulisho cha mpiga kura", "Kitambulisho cha mpiga kura"),
                    ("Sina Kitambulisho", "Sina Kitambulisho"),
                ],
                default="NIDA",
                max_length=50,
            ),
        ),
    ]
