# Generated by Django 4.1.3 on 2022-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="neighborhood", name="leader_name",),
        migrations.RemoveField(model_name="neighborhood", name="phone",),
        migrations.RemoveField(model_name="neighborhood", name="population",),
        migrations.RemoveField(model_name="village", name="population",),
        migrations.AddField(
            model_name="district",
            name="post_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="post_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="post_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="village",
            name="post_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="ward",
            name="post_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
